export const table = {
    user: 'user',
    profile: 'profile',
    userRole: 'user_role',
    loginHistory: 'login_history',
    fund: 'fund',
    verification: "verification",
    docs: "docs",
    permission: "permission",
    feature: "feature",
    language: "language",
    gender: "gender",
    ageRange: "age_range",
    mood: "mood",
    productTag: "product_tag",
    post: "post",
    postMedia: "post_media",
    postComment: "post_comment",
    profileType: "profile_type",
    postType: "post_type",
    postTrust: "post_trust",
    postReaction: "post_reaction",
    hobby: "hobby",
    respect: "respect",
    subMood: "sub_mood",
    postSubMood: "post_sub_mood",
    location: "location",
    postView: "post_view",
    challenge: "challenge",
    userChallenge: "user_challenge",
    challengeEntries: "challenge_entries",
    challengeEntriesMedia: "challenge_entries_media",
    challengeEntriesLocation: "challenge_entries_location",
    challengeEntriesReaction: "challenge_entries_reaction",
    challengeEntriesComment: "challenge_entries_comment",
    challengeEntriesView: "challenge_entries_view",
    judge: "judge",
    result: "result",
    assignJudge: "assign_judge",
    challengeRemark: "challenge_remark",
    noticeboard: "noticeboard",
    moodCategory: "mood_category",
    coin_activity_log: "coin_activity_log",
    coin_activity: "coin_activity",
    user_app_access: 'user_app_access'
};

export const dbview = {
  lastLoginAudit: 'lastLoginAudit'
};
